=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/jsonschema/bindings-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {

        "Context": {
            "$id": "#/definitions/Context",
            "type": "object",
            "title": "The Items Schema",
            "additionalProperties": { "type": "string"}
        },
        "QualifiedName": {
            "$id": "#/definitions/QualifiedName",
            "type": "string",
            "title": "The QualifiedName Schema",
            "default": "",
            "pattern": "^[A-Za-z0-9_]+:(.*)$"
        },
        "lang_string": {
            "type": "object",
            "required": [ "@value" ],
            "properties": {
                "@value": {
                    "type": "string"
                },
                "@language": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "ValuesOrIds": {
            "oneOf": [
                {
                    "$ref": "#/definitions/ArrayOfArraysOfValues"
                },
                {
                    "$ref": "#/definitions/ArrayOfIds"
                }
            ]
        },
        "ArrayOfArraysOfValues": {
            "type": "array",
            "items": [
                { "$ref": "#/definitions/ArrayOfValues" }
            ]
        },
        "ArrayOfValues": {
            "$id": "#/definitions/ArrayOfValues",
            "type": "array",
            "items": {
                "anyOf": [
                    { "$ref": "#/definitions/QualifiedName" },
                    { "$ref": "#/definitions/An@value" },
                    { "$ref": "#/definitions/An@id" },
                    { "$ref": "#/definitions/lang_string" }
                ]
            }
        },
        "ArrayOfIds": {
            "$id": "#/definitions/ArrayOfIds",
            "type": "array",
            "items": {
                "anyOf": [
                    { "$ref": "#/definitions/An@id" }
                ]
            }
        },

        "An@id":  {
            "type": "object",
            "properties": {
                "@id": {
                    "type": "string"
                },
                "@type": {
                    "type": "string"
                },
                "@documentation": {
                    "type": "string"
                },
                "@examplar": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                },
                "@input": {
                    "type": "string",
                    "enum": ["compulsory", "optional", "false"]
                },
                "@output": {
                    "type": "string",
                    "enum": ["true", "false"]
                },
                "@sql.table": {
                    "type": "string"
                }
            },
            "required": [
                "@id"
            ],
            "additionalProperties": false
        },
        "An@value": {
            "type": "object",
            "properties": {
                "@value": {
                    "type": "string"
                },
                "@type": {
                    "type": "string"
                },
                "@documentation": {
                    "type": "string"
                },
                "@examplar": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "number"
                        }
                    ]
                },
                "@input" : {
                    "type": "string",
                    "enum": ["compulsory", "optional", "false"]
                },
                "@output" : {
                    "type": "string",
                    "enum": ["true", "false"]
                },
                "@sql.type" : {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }

    },
    "type": "object",
    "properties": {
        "var": {
            "type": "object",
            "patternProperties": {
                "^(.*)$": { "$ref": "#/definitions/ValuesOrIds" }
            }
        },
        "vargen": {
            "type": "object"
        },
        "context": {
            "$ref": "#/definitions/Context"
        },
        "template": {
            "type": "string"
        }
    },
    "required": [
        "var",
        "context"
    ]
}

=== lucmoreau/ProvToolbox/modules-explanations/prov-explanations/src/test/resources/plead/bindings/128350251-rectification-4.2-accept.json
{
    "var" : {
        "institution" : [ {
            "@id" : "ex:institution"
        }],
        "application": [ {
            "@id": "ex:applications/128350251"
        }],
        "application/v1": [ {
            "@id": "ex:applications/128350251/v1"
        }],

        "applicant": [ {
            "@id": "ex:applicants/128350251"
        }],
        "staff2": [ {
            "@id": "ex:staff/112"
        }],
        "reviewing_request": [ {
            "@id": "ex:review_request/1234"
        }],
        "rectifying": [ {
            "@id": "ex:rectifying/1234"
        }],
        "rectification_review_decision": [ {
            "@id": "ex:rectification_review_decision/1234"
        }],
        "customer_request": [ {
            "@id": "ex:customer_requests/1234"
        }],
        "document": [ {
            "@id": "ex:documents/12754"
        }],
        "document_type": [ {
            "@id": "ln:Payslip"
        }],
        "document_location": [ "some/file/location" ],
        "request_reason": [ "My annual income is not correct, it is 150000 not 50000" ],
        "comment": [ "The annual income is incorrect and updated after reviewing proofs" ],
        "request_date": [[  {
            "@value": "2020-05-13T14:58:15",
            "@type": "xsd:dateTime"
        }]],
        "reviewing_start": [[  {
            "@value": "2020-05-15T14:21:00",
            "@type": "xsd:dateTime"
        }]],
        "reviewing_end": [[  {
            "@value": "2020-05-15T14:29:00",
            "@type": "xsd:dateTime"
        }]],
        "used_time": [[  {
            "@value": "2020-05-15T14:21:00",
            "@type": "xsd:dateTime"
        }]],
        "rectifying_start": [[  {
            "@value": "2020-05-15T14:29:30",
            "@type": "xsd:dateTime"
        }]],
        "rectifying_end": [[  {
            "@value": "2020-05-15T14:29:31",
            "@type": "xsd:dateTime"
        }]],
        "attr_loan_amnt": [[  {
            "@value": "12025",
            "@type": "xsd:float"
        }]],
        "attr_term": ["36 months"],
        "attr_emp_title": ["Lead Vet Tech"],
        "attr_emp_length": ["4 years"],
        "attr_home_ownership": ["RENT"],
        "attr_annual_inc":  [[  {
            "@value": "15000",
            "@type": "xsd:float"
        }]],
        "attr_purpose": ["credit_card"] ,
        "attr_title": ["Credit card refinancing"],
        "attr_zip_code": [ "950xx"],
        "attr_addr_state": ["CA"],
        "attr_application_type": ["Joint App"],
        "application_created_at": [[  {
            "@value": "2019-05-15T14:29:30",
            "@type": "xsd:dateTime"
        }]]
    },
    "vargen" : { },
    "context" : {
        "pd": "https://pandas.pydata.org/#",
        "py": "urn:python:var:",
        "sk": "https://scikit-learn.org/stable/modules/generated/sklearn.",
        "ln": "https://plead-project.org/ns/loan#",
        "pl": "https://plead-project.org/ns/plead#",
        "localfile": "file:///Users/me/mlpipeline/",
        "ex" : "http://example.org/"
    },
    "template" : "rectification-4.2-accept"
}
