=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/jsonschema/template-transformation-file-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Schema for a Template Transformation File",
    "definitions": {
        "ProvFormat": {
            "type": "string",
            "enum": ["provn", "prov-jsonld", "jsonld","svg", "png", "pdf"]
        },
        "InstantiateTask": {
            "type": "object",
            "properties": {
                "type": { "const": "instantiate" },
                "description": { "type": "string" },
                "template": { "type": "string" },
                "bindings": { "type": "string" },
                "output": { "type": "string" },
                "outputFullyQualifiedName": { "type": "string" },
                "formats": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/ProvFormat" }
                },

                "hasProvenance": {
                    "type": "string"
                },
                "addOutputDirToInputPath": {
                    "type": "boolean"
                },
                "copyinput": {
                    "type": "boolean"
                },
                "clean2": {
                    "type": "boolean"
                },
                "template_path": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ],
                    "minItems": 1
                }
            },
            "required": ["type", "template", "bindings", "output", "formats"],
            "additionalProperties": false
        },
        "MergeTask": {
            "type": "object",
            "properties": {
                "type": { "const": "merge" },
                "description": { "type": "string" },
                "inputs": {
                    "type": "array",
                    "items": { "type": "string" },
                    "minItems": 1
                },
                "output": { "type": "string" },
                "outputFullyQualifiedName": { "type": "string" },
                "formats": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/ProvFormat" }
                },

                "hasProvenance": {
                    "type": "string"
                },
                "addOutputDirToInputPath": {
                    "type": "boolean"
                },
                "copyinput": {
                    "type": "boolean"
                },
                "clean2": {
                    "type": "boolean"
                },
                "template_path": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ],
                    "minItems": 1
                }
            },
            "required": ["type", "inputs", "output", "formats"],
            "additionalProperties": false
        }
    },
    "type": "object",
    "properties": {
        "template_path": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ],
            "minItems": 1
        },
        "bindings_path": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ],
            "minItems": 1
        },
        "output_dir": {
            "type": "string"
        },
        "variableMaps": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "tasks": {
            "type": "array",
            "items": {
                "oneOf": [
                    { "$ref": "#/definitions/InstantiateTask" },
                    { "$ref": "#/definitions/MergeTask" }
                ]
            },
            "minItems": 1
        }
    },

    "required": [
        "template_path",
        "bindings_path",
        "output_dir",
        "variableMaps",
        "tasks"
    ]
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/ttfs/ttf-pg.json
{
    "template_path": ["target/generated-templates", "src/main/resources/templates"],
    "bindings_path": ["src/main/resources/bindings/pg"],
    "output_dir": ".",

    "variableMaps": ["./common-ns.json"],

    "tasks": [
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/operation",
            "output": "org/openprovenance/prov/templates/pg/pg-capturing",
            "bindings": "pg-capturing.json",
            "formats": ["provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/pg/prov/prov-pg-capturing.prov-csv"

        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/operation",
            "output": "org/openprovenance/prov/templates/pg/pg-dropping",
            "bindings": "pg-dropping.json",
            "formats": ["provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/pg/prov/prov-pg-dropping.prov-csv"

        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/operation",
            "output": "org/openprovenance/prov/templates/pg/pg-ballcollecting",
            "bindings": "pg-ballcollecting.json",
            "formats": ["provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/pg/prov/prov-pg-ballcollecting.prov-csv"

        }
    ]


}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/ttfs/ttf-ptm.json
{
    "template_path": ["target/generated-templates", "src/main/resources/templates"],
    "bindings_path": ["src/main/resources/bindings/ptm"],
    "output_dir": ".",

    "variableMaps": ["./common-ns.json"],

    "tasks": [
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/parallel2",
            "output": "org/openprovenance/prov/templates/ptm/ptm-expanding",
            "bindings": "ptm-expanding.json",
            "formats": ["provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/ptm/prov/prov-ptm-expanding.prov-csv"

        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/parallel2",
            "output": "org/openprovenance/prov/templates/ptm/ptm-merging",
            "bindings": "ptm-merging.json",
            "formats": ["provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/ptm/prov/prov-ptm-merging.prov-csv"

        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/parallel2",
            "output": "org/openprovenance/prov/templates/ptm/ptm-mexpanding",
            "bindings": "ptm-mexpanding.json",
            "formats": ["provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/ptm/prov/prov-ptm-mexpanding.prov-csv"

        }
    ]
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/ttfs/ttf-plead.json
{
    "template_path": ["src/main/resources/templates"],
    "bindings_path": ["src/main/resources/bindings/plead"],
    "output_dir": ".",

    "variableMaps": ["./common-ns.json"],

    "tasks": [
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/transforming1",
            "output": "org/openprovenance/prov/templates/plead/plead-transforming",
            "bindings": "plead-transforming.json",
            "formats": ["jsonld", "provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/plead/prov/prov-plead-transforming.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/transforming1",
            "output": "org/openprovenance/prov/templates/plead/plead-validating",
            "bindings": "plead-validating.json",
            "formats": ["provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/plead/prov/prov-plead-validating.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/transforming1",
            "output": "org/openprovenance/prov/templates/plead/plead-training",
            "bindings": "plead-training.json",
            "formats": [ "provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/plead/prov/prov-plead-training.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/transforming1",
            "output": "org/openprovenance/prov/templates/plead/plead-filtering",
            "bindings": "plead-filtering.json",
            "formats": ["provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/plead/prov/prov-plead-filtering.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/product2-2",
            "template_path": ["target/generated-templates"],
            "output": "org/openprovenance/prov/templates/plead/plead-approving",
            "bindings": "plead-approving.json",
            "formats": ["provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/plead/prov/prov-plead-approving.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/prov/templates/generic/forking2",
            "template_path": ["target/generated-templates"],
            "output": "org/openprovenance/prov/templates/plead/plead-splitting",
            "bindings": "plead-splitting.json",
            "formats": ["provn", "png"],
            "hasProvenance": "org/openprovenance/prov/templates/plead/prov/prov-plead-splitting.prov-csv"
        }
    ]


}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/meta/config/ttf-generic.json
{
    "template_path": ["src/main/resources/meta/metatemplates"],
    "bindings_path": ["src/main/resources/meta/metabindings"],
    "output_dir": "generated-templates/org/openprovenance/prov/templates/generic",

    "variableMaps": ["./common-ns.json"],

    "tasks": [
        {
            "type": "instantiate",
            "template": "transforming1.provn",
            "output": "forking2",
            "bindings": "forking2.json",
            "formats": ["provn", "png", "svg"],
            "copyinput": true,
            "hasProvenance": "prov-forking2.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "transforming1.provn",
            "output": "joining2",
            "bindings": "joining2.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "prov-joining2.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "transforming1.provn",
            "output": "parallel2",
            "bindings": "parallel2.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "prov-parallel2.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "transforming1.provn",
            "output": "product2-2",
            "bindings": "product2-2.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "prov-product2-2.prov-csv"

        },
        {
            "type": "instantiate",
            "template": "joining2.provn",
            "template_path": ["target/generated-templates/org/openprovenance/prov/templates/generic"],
            "output": "binaryop",
            "bindings": "binaryop.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "prov-binaryop.prov-csv"
        }
    ]


}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/ttfs/ttf-generic.json
{
    "template_path": ["src/main/resources/templates"],
    "bindings_path": ["src/main/resources/bindings/generic"],
    "output_dir": ".",

    "variableMaps": ["./common-ns.json"],

    "tasks": [
        {
            "type": "instantiate",
            "template": "org/openprovenance/templates/generic/transforming1",
            "output": "org/openprovenance/templates/generic/forking2",
            "bindings": "forking2.json",
            "formats": ["provn", "png", "svg"],
            "copyinput": false,
            "hasProvenance": "org/openprovenance/templates/generic/prov/prov-forking2.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/templates/generic/transforming1",
            "output": "org/openprovenance/templates/generic/joining2",
            "bindings": "joining2.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "org/openprovenance/templates/generic/prov/prov-joining2.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/templates/generic/transforming1",
            "output": "org/openprovenance/templates/generic/parallel2",
            "bindings": "parallel2.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "org/openprovenance/templates/generic/prov/prov-parallel2.prov-csv"
        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/templates/generic/transforming1",
            "output": "org/openprovenance/templates/generic/product2-2",
            "bindings": "product2-2.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "org/openprovenance/templates/generic/prov/prov-product2-2.prov-csv"

        },
        {
            "type": "instantiate",
            "template": "org/openprovenance/templates/generic/joining2",
            "template_path": ["target/generated-templates"],
            "output": "org/openprovenance/templates/generic/binaryop",
            "bindings": "binaryop.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "org/openprovenance/templates/generic/prov/prov-binaryop.prov-csv"
        }
    ]


}
