=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/jsonschema/ttb-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Schema for a Template Tasks Batch",
    "definitions": {
        "ProvFormat": {
            "type": "string",
            "enum": ["provn", "prov-jsonld", "svg", "png", "pdf"]
        },
        "Task": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["expansion", "merge"]
                },
                "description": {
                    "type": "string"
                },
                "input": {
                    "type": "string"
                },
                "input2": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                },
                "bindings": {
                    "oneOf": [
                        {"type": "string"},
                        {"type": "null"}
                    ]
                },
                "formats": {
                    "type": "array",
                    "items":  {"$ref": "#/definitions/ProvFormat"}
                },
                "hasProvenance": {
                    "type": "string"
                },
                "copyinput": {
                    "type": "boolean"
                },
                "clean2": {
                    "type": "boolean"
                },
                "template_path": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ],
                    "minItems": 1
                }
            },
            "required": [
                "type",
                "input",
                "output",
                "bindings",
                "formats"
            ],
            "additionalProperties": false
        }
    },
    "type": "object",
    "properties": {
        "template_path": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ],
            "minItems": 1
        },
        "bindings_path": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ],
            "minItems": 1
        },
        "output_dir": {
            "type": "string"
        },
        "variableMaps": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "tasks": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Task"
            },
            "minItems": 1
        }
    },

    "required": [
        "template_path",
        "bindings_path",
        "output_dir",
        "variableMaps",
        "tasks"
    ]
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/meta/config/ttb-plead.json
{
    "template_path": ["src/main/resources/meta/metatemplates"],
    "bindings_path": ["src/main/resources/meta/pleadbindings"],
    "output_dir": "generated-templates/org/openprovenance/prov/templates/plead",

    "variableMaps": ["./common-ns.json"],

    "tasks": [
        {
            "type": "expansion",
            "input": "transforming1.provn",
            "output": "plead-transforming",
            "bindings": "plead-transforming.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-plead-transforming.prov-csv"
        },
        {
            "type": "expansion",
            "input": "transforming1.provn",
            "output": "plead-validating",
            "bindings": "plead-validating.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-plead-validating.prov-csv"
        },
        {
            "type": "expansion",
            "input": "transforming1.provn",
            "output": "plead-training",
            "bindings": "plead-training.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-plead-training.prov-csv"
        },
        {
            "type": "expansion",
            "input": "transforming1.provn",
            "output": "plead-filtering",
            "bindings": "plead-filtering.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-plead-filtering.prov-csv"
        },
        {
            "type": "expansion",
            "input": "product2-2.provn",
            "template_path": ["target/generated-templates/org/openprovenance/prov/templates/generic"],
            "output": "plead-approving",
            "bindings": "plead-approving.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-plead-approving.prov-csv"
        },
        {
            "type": "expansion",
            "input": "forking2.provn",
            "template_path": ["target/generated-templates/org/openprovenance/prov/templates/generic"],
            "output": "plead-splitting",
            "bindings": "plead-splitting.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-plead-splitting.prov-csv"
        }
    ]


}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/meta/config/ttb-ptm.json
{
    "template_path": ["target/generated-templates/org/openprovenance/prov/templates/generic", "src/main/resources/meta/metatemplates"],
    "bindings_path": ["src/main/resources/meta/ptmbindings"],
    "output_dir": "generated-templates/org/openprovenance/prov/templates/ptm",

    "variableMaps": ["./common-ns.json"],

    "tasks": [
        {
            "type": "expansion",
            "input": "parallel2.provn",
            "output": "ptm-expanding",
            "bindings": "ptm-expanding.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-ptm-expanding.prov-csv"

        },
        {
            "type": "expansion",
            "input": "parallel2.provn",
            "output": "ptm-mexpanding",
            "bindings": "ptm-mexpanding.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-ptm-mexpanding.prov-csv"

        }
    ]
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/meta/config/config-pg.json
{
    "template_path": ["generated-templates/org/openprovenance/prov/templates/generic", "src/main/resources/meta/metatemplates"],
    "bindings_path": ["src/main/resources/meta/pg-bindings"],
    "output_dir": "generated-templates/org/openprovenance/prov/templates/pg",

    "variableMaps": ["./common-ns.json"],

    "tasks": [
        {
            "type": "expansion",
            "input": "operation.provn",
            "output": "pg-capturing",
            "bindings": "pg-capturing.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-pg-capturing.prov-csv"

        },
        {
            "type": "expansion",
            "input": "operation.provn",
            "output": "pg-dropping",
            "bindings": "pg-dropping.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-pg-dropping.prov-csv"

        },
        {
            "type": "expansion",
            "input": "operation.provn",
            "output": "pg-ballcollecting",
            "bindings": "pg-ballcollecting.json",
            "formats": ["provn", "png"],
            "hasProvenance": "prov-pg-ballcollecting.prov-csv"

        }
    ]


}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/meta/config/ttb-generic.json
{
    "template_path": ["src/main/resources/meta/metatemplates"],
    "bindings_path": ["src/main/resources/meta/metabindings"],
    "output_dir": "generated-templates/org/openprovenance/prov/templates/generic",

    "variableMaps": ["./common-ns.json"],

    "tasks": [
        {
            "type": "expansion",
            "input": "transforming1.provn",
            "output": "forking2",
            "bindings": "forking2.json",
            "formats": ["provn", "png", "svg"],
            "copyinput": true,
            "hasProvenance": "prov-forking2.prov-csv"
        },
        {
            "type": "expansion",
            "input": "transforming1.provn",
            "output": "joining2",
            "bindings": "joining2.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "prov-joining2.prov-csv"
        },
        {
            "type": "expansion",
            "input": "transforming1.provn",
            "output": "parallel2",
            "bindings": "parallel2.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "prov-parallel2.prov-csv"
        },
        {
            "type": "expansion",
            "input": "transforming1.provn",
            "output": "product2-2",
            "bindings": "product2-2.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "prov-product2-2.prov-csv"

        },
        {
            "type": "expansion",
            "input": "joining2.provn",
            "template_path": ["target/generated-templates/org/openprovenance/prov/templates/generic"],
            "output": "binaryop",
            "bindings": "binaryop.json",
            "formats": ["provn", "png", "svg"],
            "hasProvenance": "prov-binaryop.prov-csv"
        }
    ]


}
