=== lucmoreau/ProvToolbox/modules-template/prov-template-compiler/src/main/resources/schema/template-project-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Templates Project Schema",
    "definitions": {
        "SimpleTemplateDescriptor": {
            "type": "object",
            "properties": {
                "@type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "template": {
                    "type": "string"
                },
                "package": {
                    "type": "string"
                },
                "bindings": {
                    "type": "string"
                }
            },
            "required": [
                "@type",
                "name",
                "template",
                "package",
                "bindings"
            ],
            "additionalProperties": false
        },
        "CompositeTemplateDescriptor": {
            "type": "object",
            "properties": {
                "@type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "consistsOf": {
                    "type": "string"
                },
                "package": {
                    "type": "string"
                },
                "sharing": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "string"
                        }
                    ]
                }
            },
            "required": [
                "@type",
                "name",
                "consistsOf",
                "package",
                "sharing"
            ],
            "additionalProperties": false
        },
        "TemplateDescriptor": {
            "anyOf": [
                {
                    "$ref": "#/definitions/SimpleTemplateDescriptor"
                },
                {
                    "$ref": "#/definitions/CompositeTemplateDescriptor"
                }
            ]
        },
        "TableDescriptor": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "serial": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "created_at"
            ],
            "additionalProperties": false
        }
    },
    "type": "object",
    "properties": {
        "group": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "destination": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "version": {
            "type": "string"
        },
        "root_package": {
            "type": "string"
        },
        "script": {
            "type": "string"
        },
        "script_dir": {
            "type": "string"
        },
        "python_dir": {
            "type": "string"
        },
        "integrator": {
            "type": "boolean"
        },
        "sbean": {
            "type": "boolean"
        },
        "jsweet": {
            "type": "boolean"
        },
        "jsonschema": {
            "type": "string"
        },
        "documentation": {
            "type": "string"
        },
        "sqlFile": {
            "type": "string"
        },
        "templates": {
            "type": "array",
            "items": [
                {
                    "$ref": "#/definitions/TemplateDescriptor"
                }
            ]
        },
        "search": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "sql.tables": {
            "type": "object",
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/TableDescriptor"
                }
            }
        }
    },
    "required": [
        "group",
        "name",
        "destination",
        "description",
        "version",
        "root_package",
        "script",
        "script_dir",
        "python_dir",
        "sbean",
        "jsweet",
        "jsonschema",
        "documentation",

        "templates"
    ],
    "additionalProperties": false
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/config/tp_ptm.json
{
	"group": "org.openprovenance.prov",
	"name": "template_library",
	"destination": "target",
	"description": "PROV templates for prov template management",
	"version": "0.1.0",
	"root_package": "org.openprovenance.prov.template.library.ptm",
	"script": "tmp_run",
	"script_dir": "target/bin",
	"python_dir": "target/generated-python",
	"integrator": true,
	"sbean": true,
	"jsweet": true,
	"jsonschema": "schema-ptm.json",
	"documentation": "doc-ptm.html",
	"sqlFile": "prov-template-library-ptm.sql",
	"templates" : [


		{
			"@type": "simple",
			"name": "ptm_expanding",
			"template": "target/prov-template-library/templates/org/openprovenance/prov/templates/ptm/ptm-expanding.provn",
			"package": "org.openprovenance.prov.template.library.ptm",
			"bindings": "src/main/resources/bindings/org/openprovenance/prov/templates/ptm/ptm-expanding.json"
		},
		{
			"@type": "simple",
			"name": "ptm_mexpanding",
			"template": "target/prov-template-library/templates/org/openprovenance/prov/templates/ptm/ptm-mexpanding.provn",
			"package": "org.openprovenance.prov.template.library.ptm",
			"bindings": "src/main/resources/bindings/org/openprovenance/prov/templates/ptm/ptm-mexpanding.json"
		}

	],
	"sql.tables":  {
		"activity": {
			"id": "SERIAL",
			"created_at": "timestamp with time zone NOT NULL DEFAULT NOW()"
		},
		"file": {
			"id": "SERIAL",
			"created_at": "timestamp with time zone NOT NULL DEFAULT NOW()"
		}

	}
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-compiler/src/test/resources/config1.json
{
    "group": "org.example",
    "name": "templates",
    "destination": "target/libs",
    "description": "PROV template demo",
    "version": "0.1.0",
    "script": "example_run",
    "root_package": "org.example.templates.block",
    "script_dir": "target/libs/bin",
    "python_dir": "target/libs/python",
    "jsweet": true,
    "sbean": true,
    "jsonschema": "schema.json",
    "sqlFile": "template.sql",
    "documentation": "doc.html",
    "templates" : [
        {
            "@type": "simple",
            "name": "template_block",
            "template": "src/test/resources/templates/generic_binaryop.provn",
            "package": "org.example.templates.block",
            "bindings": "src/test/resources/templates/generic_binaryop_b1.json"

        }
    ]
}
