=== lucmoreau/ProvToolbox/modules-explanations/nlg-spec-transformer/src/test/resources/jsonschema/xplan.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "definitions" : {
        "Determiner": {
            "description": "a determiner",
            "type": "string"
        },
        "Phrase": {
            "OneOf": [
                {
                    "$ref": "#/definitions/Clause"
                }
            ]
        },
        "Verb": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Clause"
                }
            ]
        },
        "Object": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Funcall"
                },
                {
                    "$ref": "#/definitions/Clause"
                }
            ]
        },
        "Clause": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["clause", "noun_phrase", "verb_phrase", "coordinated_phrase", "preposition_phrase"]
                },
                "determiner": {
                    "$ref": "#/definitions/Determiner"
                },
                "subject": {
                    "$ref": "#/definitions/Phrase"
                },
                "indirect_object": {
                    "$ref": "#/definitions/Phrase"
                },
                "object": {
                    "$ref": "#/definitions/Object"
                },
                "verb": {
                    "$ref": "#/definitions/Verb"
                },
                "head":  {
                    "$ref": "#/definitions/Head"
                },
                "conjunction": {
                    "type": "string"
                },
                "coordinates": {
                    "$ref": "#/definitions/ArrayOfClause"
                },
                "complements": {
                    "$ref": "#/definitions/Complements"
                },
                "front-modifiers": {
                    "$ref": "#/definitions/PreModifiers"
                },
                "pre-modifiers": {
                    "$ref": "#/definitions/PreModifiers"
                },
                "post-modifiers": {
                    "$ref": "#/definitions/PostModifiers"
                },
                "modifiers": {
                    "$ref": "#/definitions/Modifiers"
                },
                "@iterator": {
                    "type": "object"
                },
                "features": {
                    "$ref": "#/definitions/Features"
                }
            },
            "required": [
                "type"
            ],
            "additionalProperties": false
        },
        "StringArray": {
            "description" : "an array of strings",
            "type": "array",
            "items": {
                "type" : "string"
            }
        },
        "Funcall": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["@funcall"]
                },
                "@object": {
                    "type": "string"
                },
                "@field": {
                    "type": "string"
                },
                "@function": {
                    "type": "string"
                },
                "@arg1": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "type",
                "@object",
                "@field",
                "@function"
            ]
        },
        "StringOrFuncall": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Funcall"
                }
            ]
        },
        "Head": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Funcall"
                }
            ]
        },
        "ArrayOfClause": {
            "description" : "an array of clause",
            "type": "array",
            "items": {
                "type" : "object"
            }
        },
        "ArrayOfWhere": {
            "description" : "an array of where clause",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Clause"
            }
        },
        "Query": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/StringArray"
                }
            ]
        },

        "Complements": {
            "OneOf": [
                {
                    "type": "array"
                },
                {
                    "type": "object"
                }
            ]
        },
        "Features": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "tense": {
                    "type": "string"
                },
                "passive": {
                    "type": "string"
                },
                "number": {
                    "$ref": "#/definitions/StringOrFuncall"
                },
                "head_markup_element": {
                    "type": "string"
                },
                "head_markup_attributes": {
                    "$ref": "#/definitions/Funcall"
                }
            },
            "additionalProperties": false
        },
        "PreModifiers": {
            "type": "array"
        },
        "Modifiers": {
            "type": "array"
        },
        "PostModifiers": {
            "type": "array"
        }
    },
    "properties": {
        "select": {
            "type": "object"
        },
        "query": {
            "$ref": "#/definitions/Query"
        },
        "where": {
            "$ref": "#/definitions/ArrayOfClause"
        },
        "sentence": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["paragraph", "clause", "coordinated_phrase"]
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Clause"
                    }
                },
                "properties": {
                    "type": "object"
                },
                "subject": {
                    "$ref": "#/definitions/Clause"
                },
                "object": {
                    "$ref": "#/definitions/Object"
                },
                "indirect_object": {
                    "$ref": "#/definitions/Phrase"
                },
                "verb": {
                    "type": "string"
                },
                "features": {
                    "$ref": "#/definitions/Features"
                },
                "complements": {
                    "$ref": "#/definitions/Complements"
                },
                "modifiers": {
                    "$ref": "#/definitions/Modifiers"
                },
                "post-modifiers": {
                    "$ref": "#/definitions/PostModifiers"
                },
                "conjunction": {
                    "type": "string"
                },
                "coordinates": {
                    "$ref": "#/definitions/ArrayOfClause"
                }
            },
            "additionalProperties": false
        },
        "context": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        }
    },
    "required": [
        "select",
        "sentence",
        "context"
    ],
    "additionalProperties": false
}

=== lucmoreau/ProvToolbox/modules-explanations/nlg-spec-transformer/src/test/resources/nlg/templates/todelete/loan.origin/data.sources1.json
{

    "select": {"decision":       {"@type": "prov:Entity"}},

    "query": [
	"prefix ln <https://plead-project.org/ns/loan#>",
	
	"select * from der1 a prov:WasDerivedFrom",
	"from decision a prov:Entity",
	" join der1.generatedEntity=decision.id",
	"from application a prov:Entity",
	" join der1.usedEntity=application.id",

	"from der2 a prov:WasDerivedFrom",
	" join decision.id=der2.generatedEntity",
	"from fico a prov:Entity",
	" join der2.usedEntity=fico.id",
	"from reviewing a prov:Activity",
	" join der2.activity=reviewing.id",

	"from der4 a prov:WasDerivedFrom",
	" join decision.id=der4.generatedEntity",
	"from credit a prov:Entity",
	" join der4.usedEntity=credit.id",

	"from wat1 a prov:WasAttributedTo",
	" join credit.id=wat1.entity",
	"from creditAgency a prov:Agent",
	" join wat1.agent = creditAgency.id",

	"from wat2 a prov:WasAttributedTo",
	" join fico.id=wat2.entity",
	"from creditAgency2 a prov:Agent",
	" join wat2.agent = creditAgency2.id",

	"where decision[prov:type]    >= 'ln:HumanDecision'",
	"  and application[prov:type] >= 'ln:LoanApplication'",
	"  and reviewing[prov:type]   >= 'ln:LoanAssessment'",
	"  and fico[prov:type]        >= 'ln:FICOScore'  ",
	"  and credit[prov:type]      >= 'ln:CreditReference'",
	"  and creditAgency[prov:type]      >= 'ln:CreditReferencingAgency'    ",
	"  and creditAgency2[prov:type]      >= 'ln:CreditReferencingAgency'    "
    ],

    "sentence": {
	"type": "clause",
	"subject": {"type": "noun_phrase",
		    "determiner": "the",
		    "features": {"number": "plural"},
		    "head": "source",
		    "pre-modifiers": [{"type":"adjective_phrase",
				       "head":"data"}]
		   },
	"object": {
	    "type": "coordinated_phrase",
	    "conjunction": "and",
	    "coordinates": [
		{"type": "noun_phrase",
		 "determiner": "the",
		 "post-modifiers": [{"type":"noun_phrase",
				     "head": {"@object": "application",
					      "@field":  "id",
					      "@function": "noun+localname",
					      "@arg1": ""}},
				    {"type":"adjective_phrase",
				     "head":"provided",
				     "post-modifiers": [
					 {"type":"preposition_phrase",
					  "noun": "you",
					  "preposition": "by"}
				     ]
				    }
				   ],
		 "head": "loan application"},
		{"type": "noun_phrase",
		 "determiner": "a",
		 "post-modifiers": [{"type":"noun_phrase",
				     "head": {"@object": "credit",
					      "@field":  "id",
					      "@function": "noun+localname",
					      "@arg1": ""}},
				    {"type":"adjective_phrase",
				     "head":"provided",
				     "post-modifiers": [
					 {"type":"preposition_phrase",
					  "preposition": "by",
					  "noun": {"type":"noun_phrase",
						   "determiner": "the",
						   "head": {"@object": "creditAgency",
							    "@field":  "id",
							    "@function": "noun+localname",
							    "@arg1": "credit agency"}}},
					 {"type": "preposition_phrase",
					  "preposition": "at",
					  "noun": {"@object": "credit",
						   "@property": "ln:created_at",
						   "@optional": "true",				
						   "@function": "timestring"}}
				     ]
				    }
				   ],
		 "head": "credit reference"},
		{"type":"noun_phrase",
		 "determiner": "a",					 
		 "head": {"@object": "fico",
			  "@field":  "id",
			  "@function": "noun+localname",
			  "@arg1": "fico score"},
		 "post-modifiers": [{"type":"adjective_phrase",
				     "head":"provided",
				     "post-modifiers": [
					 {"type":"preposition_phrase",
					  "preposition": "by",
					  "noun": {"type":"noun_phrase",
						   "determiner": "the",
						   "head": {"@object": "creditAgency2",
							    "@field":  "id",
							    "@function": "noun+localname",
							    "@arg1": "credit agency"}}},
					 {"type": "preposition_phrase",
					  "preposition": "at",
					  "noun": {"@object": "fico",
						   "@property": "ln:created_at",
						   "@optional": "true",				
						   "@function": "timestring"}}
				     ]
				    }
				   ]}
	    ]
	},

	"verb": "is",
	
	"features" : {"tense": "past"}

	
    },

    "context": {
	"ex": "http://example.org/#",	
	"foaf": "http://xmlns.com/foaf/0.1/",
	"ln": "https://plead-project.org/ns/loan#",
	"pd": "https://pandas.pydata.org/#"
    }
    
    
}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/collabmap/entity1.json
{

	"select": {"ent": {"@type": "prov:Entity"}},

	"query": "select * from ent a prov:Entity",


	"sentence": {
		"type": "clause",
		"subject": {
			"type": "noun_phrase",
			"head": {
				"type": "@funcall",
				"@object": "ent",
				"@field":  "id",
				"@function": "localname"
			},
			"features": {
				"number": {
					"type": "@funcall",
					"@object": "ent",
					"@field": "id",
					"@function": "pluralp"}}},
		"verb": "be",
		"object": {
			"type": "@funcall",
			"@object": "ent",
			"@property": "prov:type",
			"@function": "lookup-type",
			"@arg1": "noun_phrase",
			"@arg2": "collabmap"
		},
		"features" : {
			"tense": "present"
		}

	},

	"context": {
		"ex": "http://example.org/#",
		"collabmap": "http://www.orchid.ac.uk/ontologies/collabmap.owl#"
	}


}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/provbasic/entity1.json
{

    "select": {"ent": {"@type": "prov:Entity"}},

    "query": "select * from ent a prov:Entity",

 
    "sentence": {
	"type": "clause",
	"subject": {"type": "noun_phrase",
		    "head": {"type": "@funcall",
			     "@object": "ent",
			     "@field":  "id",
			     "@function": "localname"},
		    "features": {"number": {"type": "@funcall",
					    "@object": "ent",
					    "@field": "id",
					    "@function": "pluralp"}}},
	"verb": "be",
	"object": {"type":"noun_phrase",
		   "head":"entity",
		   "determiner":"a"},
	"features" : {"tense": "present"}

    },

    "context": {
	"ex": "http://example.org/#"
    }
    
    
}

=== lucmoreau/ProvToolbox/modules-explanations/nlg-spec-transformer/src/test/resources/nlg/templates/todelete/loan.latest/performance2.json
{
    "select": {"pipeline": {"@type": "prov:Entity"}},

    "query": [

	"prefix ln <https://plead-project.org/ns/loan#>",
	"prefix sk <https://scikit-learn.org/stable/modules/generated/sklearn.>",
	"prefix pl <https://plead-project.org/ns/plead#>",

	"select * from pipeline a prov:Entity",
	"from wdf a prov:WasDerivedFrom",
	" join pipeline.id=wdf.usedEntity",
	"from score a prov:Entity",
	" join wdf.generatedEntity=score.id",
	"from wgb a prov:WasGeneratedBy",
	" join score.id=wgb.entity",
	"from assessing a prov:Activity",
	" join wgb.activity=assessing.id",
	"from usd a prov:Used",
	" join assessing.id=usd.activity",
	"from waw a prov:WasAssociatedWith",
	" join assessing.id=waw.activity",
	"from agent a prov:Agent",
	" join waw.agent=agent.id",

	"where pipeline[prov:type] >= 'sk:pipeline.Pipeline'",
	"and      score[prov:type] >= 'pl:AccuracyScore'",
	"and  assessing[prov:type] >= 'pl:AssessingPerformance'",
	"and      agent[prov:type] >= 'prov:Person'",
	"and   pipeline.id=usd.entity"


    ],

    "sentence": {
	"type": "clause",
	"subject": {"type": "noun_phrase",
		    "head": "data engineer",
		    "post-modifiers": [
			{"type":"adjective_phrase",
			 "head": {"@object": "agent",
				  "@field":  "id",
				  "@function": "noun+localname",
				  "@arg1": ""}}
		    ]},
	"verb": "assess",
	"object": {"type": "noun_phrase",
		   "determiner": "the",
		   "head": {"@object": "pipeline",
			    "@field":  "id",
			    "@function": "noun+localname",
			    "@arg1": "decision pipeline"}},
	
	"features" : {"tense": "past", "passive": "true"}

    },

    "context": {}
    
    
}

=== lucmoreau/ProvToolbox/modules-explanations/prov-explanations/src/main/resources/nlg/templates/plead.cs/plead.cs-1c.json
{
  "select": {
    "decision": {
      "@type": "prov:Entity"
    },
    "request": {
      "@type": "prov:Entity"
    },
    "officer": {
      "@type": "prov:Agent"
    },
    "reviewing": {
      "@type": "prov:Activity"
    },
    "assoc": {
      "@type": "prov:WasAssociatedWith"
    },
    "der1": {
      "@type": "prov:WasDerivedFrom"
    }
  },
  "query": [
    "prefix cs <http://openprovenance.org/ns/creditscoring#>",
    "prefix pl <http://openprovenance.org/ns/plead#>",
    "prefix app <https://explain.openprovenance.org/creditscoring/>",
    "select * from decision a prov:Entity",
    "from der1 a prov:WasDerivedFrom",
    "join decision.id = der1.generatedEntity",
    "from recommendation a prov:Entity",
    "join der1.usedEntity = recommendation.id",
    "from der2 a prov:WasDerivedFrom",
    "join recommendation.id = der2.generatedEntity",
    "from credit_history a prov:Entity",
    "join der2.usedEntity = credit_history.id",
    "where decision[prov:type] >= 'pl:RejectionDecision'",
    "and recommendation[prov:type] >= 'pl:AutomatedRecommendation'",
    "and credit_history[prov:type] >= 'cs:CreditHistory'"
  ],
  "sentence": {
    "type": "paragraph",
    "items": [
      {
        "type": "clause",
        "subject": {
          "type": "noun_phrase",
          "head": "credit score",
          "specifier": "##borrower-possessive"
        },
        "verb": "is",
        "object": {
          "type": "noun_phrase",
          "head": {
            "type": "@funcall",
            "@object": "credit_history",
            "@property": "cs:credit_score",
            "@function": "identity"
          },
          "features": {
            "head_markup_element": "span",
            "head_markup_attributes": {
              "type": "@funcall",
              "@object": "credit_history",
              "@function": "markup-for-id",
              "@field": "id",
              "@arg1": "provelement"
            }
          }
        }
      },
      {
        "type": "clause",
        "verb": "calculate",
        "object": {
          "type": "noun_phrase",
          "determiner": "this",
          "head": "credit score"
        },
        "indirect_object": {
          "type": "clause",
          "subject": {
            "type": "noun_phrase",
            "head": "data",
            "post-modifiers": [
              {
                "type": "preposition_phrase",
                "preposition": "from",
                "noun": "the categories"
              },
              {
                "type": "verb_phrase",
                "head": "described",
                "features": {
                  "type": "features",
                  "tense": "past"
                },
                "post-modifiers": [
                  {
                    "type": "preposition_phrase",
                    "preposition": "in",
                    "noun": "this policy"
                  }
                ]
              }
            ]
          },
          "complementiser": "using"
        },
        "features": {
          "type": "features",
          "tense": "past",
          "passive": "true"
        }
      },
      {
        "type": "clause",
        "subject": {
          "type": "noun_phrase",
          "head": "credit score",
          "specifier": "##borrower-possessive"
        },
        "verb": {
          "type": "verb_phrase",
          "head": "is",
          "post-modifiers": [
            {
              "type": "preposition_phrase",
              "preposition": "below",
              "noun": {
                "type": "noun_phrase",
                "determiner": "the",
                "head": "acceptance threshold",
                "post-modifiers": [
                  {
                    "type": "preposition_phrase",
                    "preposition": "of",
                    "noun": {
                      "type": "noun_phrase",
                      "head": {
                        "type": "@funcall",
                        "@object": "recommendation",
                        "@property": "cs:credit_score_threshold",
                        "@function": "identity"
                      },
                      "features": {
                        "head_markup_element": "span",
                        "head_markup_attributes": {
                          "type": "@funcall",
                          "@object": "recommendation",
                          "@function": "markup-for-id",
                          "@field": "id",
                          "@arg1": "provelement"
                        }
                      }
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    ],
    "properties": {}
  },
  "context": {
    "ex": "http://example.org/#",
    "app": "https://explain.openprovenance.org/creditscoring/",
    "pl": "http://openprovenance.org/ns/plead#",
    "cs": "http://openprovenance.org/ns/creditscoring#"
  }
}

=== lucmoreau/ProvToolbox/modules-explanations/prov-explanations/src/main/resources/nlg/templates/thump/thump.plan.failure1b.json
{

	"select": {
		"plan1":        {"@type": "prov:Entity"},
		"plan2":        {"@type": "prov:Entity"},
		"ag":           {"@type": "prov:Agent"}
		},
	"query": [
		"prefix ros <https://openprovenance.org/ns/ros>",
		"prefix rpl <http://openprovenance.org/ns/rosplan>",
		"prefix rs <urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/>",
		"prefix rn <urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/nodes/>",
		"prefix msg <urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/messages/>",
		"prefix ex <http://example.org/>",

		"prefix pl <https://plead-project.org/ns/plead#>",

		"select * from wdf a prov:WasDerivedFrom",
		"from plan1 a prov:Entity",
		" join wdf.usedEntity = plan1.id",
		"from plan2 a prov:Entity",
		" join wdf.generatedEntity=plan2.id",
		"from usd a prov:Used",
		" join plan1.id = usd.entity",
		"from dispatching a prov:Activity",
		" join usd.activity=dispatching.id",
		"from waw a prov:WasAssociatedWith",
		" join dispatching.id=waw.activity",
		"from ag a prov:Agent",
		" join waw.agent=ag.id",
		"from mem a provext:HadMember",
		" join plan2.id=mem.collection",
		"from action a prov:Entity",
		" join mem.element=action.id",

		"where plan2[prov:type]       >= 'rpl:CancelledPlan'",
		"  and plan1[prov:type]       >= 'rpl:EsterelPlan'",
		"  and ag[prov:type]          >= 'rpl:ROSPlanNode'",
		"  and dispatching[prov:type] >= 'ex:DispatchingPlan'",
		"  and action[prov:type]      >= 'rpl:CancelledAction'",

		"group by plan1, plan2, ag aggregate action with Seq"

	],




	"sentence": {
		"type": "clause",
		"object": {
			"type": "noun_phrase",

			"head": {
				"type": "@funcall",
				"@object": "plan2",
				"@field":  "id",
				"@function": "noun+localname",
				"@arg1":   "plan"
			}
		},
		"subject": {
			"type": "coordinated_phrase",
			"conjunction": "and",
			"@iterator": {
				"type": "@iterator",
				"@variable": "action",
				"@clause": "coordinates",
				"@element": {
					"type": "noun_phrase",
					"head": {
						"type": "@funcall",
						"@object": "action",
						"@field":  "id",
						"@function": "noun+localname",
						"@arg1":   "action"
					}
				}
			}

		},

		"verb": "fail",
		"features" : {
			"tense": "past",
			"passive": "true"
		}


	},

	"context": {
		"ex": "http://example.org/#",
		"foaf": "http://xmlns.com/foaf/0.1/",
		"ln": "https://plead-project.org/ns/loan#",
		"pl": "https://plead-project.org/ns/plead#",
		"pd": "https://pandas.pydata.org/#",
		"ros": "https://openprovenance.org/ns/ros",
		"rpl": "http://openprovenance.org/ns/rosplan",
		"rs": "urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2",
		"rn": "urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/nodes/",
		"msg": "urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/messages/"


	}


}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/collabmap/actedonbehalfof1.json
{

    "select": {"aobo": {"@type": "prov:ActedOnBehalfOf"}},

    "query": "select * from aobo a prov:ActedOnBehalfOf",        
 
    "sentence": {
	"type": "clause",
	"subject":  {"type": "noun_phrase",
		     "head": {"type": "@funcall",
			      "@object": "aobo",
			      "@field":  "delegate",
			      "@function": "localname"},
		    "features": {"number": {"type": "@funcall",
					    "@object": "aobo",
					    "@field": "delegate",
					    "@function": "pluralp"}}},
	"verb": "act",
	"modifiers": [{"type": "preposition_phrase",
		       "preposition": "on behalf of",
		       "noun": {"type": "@funcall",
				"@object": "aobo",
				"@field": "responsible",
				"@function": "localname"}}],	
	"features" : {"tense": "past"}

    },

    "context": {
	"ex": "http://example.org/#"
    }
    
}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/baking/baking-generation1.json
{

    "select": {"gen": {"@type": "prov:WasGeneratedBy"},
	       "act": {"@type": "prov:Activity"}},


    "query": [
	"prefix ex <http://example.org/#>",
	"select * from gen a prov:WasGeneratedBy",
	"from act a prov:Activity",
	"join gen.activity = act.id",
	"where act[prov:type] >= 'ex:Baking' "],

    "where": [{"@object": "act",
	       "@property":  "prov:type",
	       "@function":  "equalsQualifiedName",
	       "@arg1":     "ex:Baking"},
	      {"@object": "act",
	       "@field":  "id",
	       "@function":  "equals",
	       "@object1":     "gen",
	       "@field1":     "activity"}],    

    "sentence": {
	"type": "clause",
	"object":  {"type": "noun_phrase",
		    "head": {"type": "@funcall",
			     "@object": "gen",
			     "@field":  "entity",
			     "@function": "localname"},
		    "features": {"number": {"type": "@funcall",
					    "@object": "gen",
					    "@field": "entity",
					    "@function": "pluralp"}}},
	"verb": "bake",
	"modifiers": [{"type": "preposition_phrase",
		       "preposition": "during",
		       "noun": {"type": "@funcall",
				"@object": "gen",
				"@field": "activity",
				"@optional": "true",				
				"@function": "localname"}},
		      {"type": "preposition_phrase",
		       "preposition": "at",
		       "noun": {"type": "@funcall",
				"@object": "gen",
				"@field": "time",
				"@optional": "true",				
				"@function": "timestring"}}],	
	"features" : {"tense": "past",
		      "passive": "true"}

    },

    "context": {
	"ex": "http://example.org/#"
    }
    
    
}
