=== lucmoreau/ProvToolbox/modules-explanations/nlg-spec-transformer/src/test/resources/jsonschema/xplan.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "definitions" : {
        "Determiner": {
            "description": "a determiner",
            "type": "string"
        },
        "Phrase": {
            "OneOf": [
                {
                    "$ref": "#/definitions/Clause"
                }
            ]
        },
        "Verb": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Clause"
                }
            ]
        },
        "Object": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Funcall"
                },
                {
                    "$ref": "#/definitions/Clause"
                }
            ]
        },
        "Clause": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["clause", "noun_phrase", "verb_phrase", "coordinated_phrase", "preposition_phrase"]
                },
                "determiner": {
                    "$ref": "#/definitions/Determiner"
                },
                "subject": {
                    "$ref": "#/definitions/Phrase"
                },
                "indirect_object": {
                    "$ref": "#/definitions/Phrase"
                },
                "object": {
                    "$ref": "#/definitions/Object"
                },
                "verb": {
                    "$ref": "#/definitions/Verb"
                },
                "head":  {
                    "$ref": "#/definitions/Head"
                },
                "conjunction": {
                    "type": "string"
                },
                "coordinates": {
                    "$ref": "#/definitions/ArrayOfClause"
                },
                "complements": {
                    "$ref": "#/definitions/Complements"
                },
                "front-modifiers": {
                    "$ref": "#/definitions/PreModifiers"
                },
                "pre-modifiers": {
                    "$ref": "#/definitions/PreModifiers"
                },
                "post-modifiers": {
                    "$ref": "#/definitions/PostModifiers"
                },
                "modifiers": {
                    "$ref": "#/definitions/Modifiers"
                },
                "@iterator": {
                    "type": "object"
                },
                "features": {
                    "$ref": "#/definitions/Features"
                }
            },
            "required": [
                "type"
            ],
            "additionalProperties": false
        },
        "StringArray": {
            "description" : "an array of strings",
            "type": "array",
            "items": {
                "type" : "string"
            }
        },
        "Funcall": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["@funcall"]
                },
                "@object": {
                    "type": "string"
                },
                "@field": {
                    "type": "string"
                },
                "@function": {
                    "type": "string"
                },
                "@arg1": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "type",
                "@object",
                "@field",
                "@function"
            ]
        },
        "StringOrFuncall": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Funcall"
                }
            ]
        },
        "Head": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Funcall"
                }
            ]
        },
        "ArrayOfClause": {
            "description" : "an array of clause",
            "type": "array",
            "items": {
                "type" : "object"
            }
        },
        "ArrayOfWhere": {
            "description" : "an array of where clause",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Clause"
            }
        },
        "Query": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/StringArray"
                }
            ]
        },

        "Complements": {
            "OneOf": [
                {
                    "type": "array"
                },
                {
                    "type": "object"
                }
            ]
        },
        "Features": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "tense": {
                    "type": "string"
                },
                "passive": {
                    "type": "string"
                },
                "number": {
                    "$ref": "#/definitions/StringOrFuncall"
                },
                "head_markup_element": {
                    "type": "string"
                },
                "head_markup_attributes": {
                    "$ref": "#/definitions/Funcall"
                }
            },
            "additionalProperties": false
        },
        "PreModifiers": {
            "type": "array"
        },
        "Modifiers": {
            "type": "array"
        },
        "PostModifiers": {
            "type": "array"
        }
    },
    "properties": {
        "select": {
            "type": "object"
        },
        "query": {
            "$ref": "#/definitions/Query"
        },
        "where": {
            "$ref": "#/definitions/ArrayOfClause"
        },
        "sentence": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["paragraph", "clause", "coordinated_phrase"]
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Clause"
                    }
                },
                "properties": {
                    "type": "object"
                },
                "subject": {
                    "$ref": "#/definitions/Clause"
                },
                "object": {
                    "$ref": "#/definitions/Object"
                },
                "indirect_object": {
                    "$ref": "#/definitions/Phrase"
                },
                "verb": {
                    "type": "string"
                },
                "features": {
                    "$ref": "#/definitions/Features"
                },
                "complements": {
                    "$ref": "#/definitions/Complements"
                },
                "modifiers": {
                    "$ref": "#/definitions/Modifiers"
                },
                "post-modifiers": {
                    "$ref": "#/definitions/PostModifiers"
                },
                "conjunction": {
                    "type": "string"
                },
                "coordinates": {
                    "$ref": "#/definitions/ArrayOfClause"
                }
            },
            "additionalProperties": false
        },
        "context": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        }
    },
    "required": [
        "select",
        "sentence",
        "context"
    ],
    "additionalProperties": false
}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/collabmap/member1.json
{

    "select": {"mem": {"@type": "provext:HadMember"}},

    "query": "select * from mem a provext:HadMember",        
 
 
    "sentence": {
	"type": "clause",
	"subject":  {"type": "noun_phrase",
		     "head": {"type": "@funcall",
			      "@object": "mem",
			      "@field":  "entity",
			      "@function": "localname"},
		     "features": {"number": {"type": "@funcall",
					     "@object": "mem",
					     "@field": "entity",
					     "@function": "pluralp"}}},
	"verb": "is member",
	"modifiers": [{"type": "preposition_phrase",
		       "preposition": "of",
		       "noun": {"type": "@funcall",
				"@object": "mem",
				"@field": "collection",
				"@function": "localname"}}],	
	"features" : {"tense": "past"}

    },

    "context": {
	"ex": "http://example.org/#"
    }
    
}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/thump/thump.plan.models1b.json
{

	"select": {
		"plan1":        {"@type": "prov:Entity"},
		"plan2":        {"@type": "prov:Entity"},
		"ag":           {"@type": "prov:Agent"}
		},
	"query": [
		"prefix ros <https://openprovenance.org/ns/ros>",
		"prefix rpl <http://openprovenance.org/ns/rosplan>",
		"prefix rs <urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/>",
		"prefix rn <urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/nodes/>",
		"prefix msg <urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/messages/>",
		"prefix ex <http://example.org/>",

		"prefix pl <https://plead-project.org/ns/plead#>",

		"select * from (",
		"  select * from wdf a provext:WasDerivedFromStar",
		"  from plan a prov:Entity",
		"   join wdf.generatedEntity=plan.id",
		"  from model a prov:Entity",
		"   join wdf.usedEntity=model.id",


		"  where plan[prov:type]       >= 'rpl:EsterelPlan'",
		"    and model[prov:type]      >= 'ex:PDDLFile'",

		"  group by plan aggregate model with Seq",
		")",

		"from (",
		"  select * from wdf a provext:WasDerivedFromStar",
		"  from plan_ a prov:Entity",
		"   join wdf.generatedEntity=plan_.id",
		"  from model_ag a prov:Entity",
		"   join wdf.usedEntity=model_ag.id",
		"  from wgb a prov:WasGeneratedBy",
		"   join model_ag.id=wgb.entity",
		"  from activity a prov:Activity",
		"   join wgb.activity=activity.id",
		"  from waw a prov:WasAssociatedWith",
		"   join activity.id=waw.activity",
		"  from agent a prov:Agent",
		"   join waw.agent=agent.id",


		"  where plan_[prov:type]      >= 'rpl:EsterelPlan'",
		"    and model_ag[prov:type]   >= 'ex:PDDLFile'",

		"  group by plan_ aggregate model_ag, activity, agent with Seq",
		")",
		"join plan.id=plan_.id"
	],




	"sentence": {
		"type": "clause",
		"object": {
			"type": "noun_phrase",

			"head": {
				"type": "@funcall",
				"@object": "plan",
				"@field":  "id",
				"@function": "noun+localname",
				"@arg1":   "plan"
			}
		},
		"subject": {
			"type": "coordinated_phrase",
			"conjunction": "and",
			"@iterator": {
				"type": "@iterator",
				"@variable": "model_ag,agent",
				"@clause": "coordinates",
				"@element": {
					"type": "noun_phrase",
					"head": {
						"type": "@funcall",
						"@object": "model_ag",
						"@field":  "id",
						"@function": "noun+localname",
						"@arg1":   "model"
					},
					"post-modifiers": [{
						"type":"adjective_phrase",
						"head": "constructed",
						"post-modifiers": [{
							"type": "preposition_phrase",
							"preposition": "by",
							"noun":  {
								"type": "noun_phrase",

								"head": {
									"type": "@funcall",
									"@object": "agent",
									"@field":  "id",
									"@function": "noun+localname",
									"@arg1":   "agent"
								}
							}}]
					}]
				}
			}

		},

		"verb": "influence",
		"features" : {
			"tense": "past",
			"passive": "true"
		}


	},

	"context": {
		"ex": "http://example.org/#",
		"foaf": "http://xmlns.com/foaf/0.1/",
		"ln": "https://plead-project.org/ns/loan#",
		"pl": "https://plead-project.org/ns/plead#",
		"pd": "https://pandas.pydata.org/#",
		"ros": "https://openprovenance.org/ns/ros",
		"rpl": "http://openprovenance.org/ns/rosplan",
		"rs": "urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2",
		"rn": "urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/nodes/",
		"msg": "urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/messages/"


	}


}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/loan/automatic.decision3.json
{

    "select": {"decision":       {"@type": "prov:Entity"}},

    "query": [

	"prefix ln <https://plead-project.org/ns/loan#>",
	"prefix pl <https://plead-project.org/ns/plead#>",


	"select * from (",
	"     select * from features a prov:Entity",

	"     from der1 a prov:WasDerivedFrom",
	"      join features.id=der1.generatedEntity",

	"     from ourdata a prov:Entity",
	"      join der1.usedEntity=ourdata.id",

	"     from der2 a prov:WasDerivedFrom",
	"      join features.id=der2.usedEntity",

	"     from recommendation a prov:Entity",
	"      join der2.generatedEntity=recommendation.id",

	"     from der3 a prov:WasDerivedFrom",
	"      join recommendation.id=der3.usedEntity",

	"     from decision a prov:Entity",
	"      join der3.generatedEntity=decision.id",


	"     from der4 a prov:WasDerivedFrom",
	"      join decision.id=der4.generatedEntity",

	"     from application a prov:Entity",
	"      join der4.usedEntity=application.id",


	"     where decision[prov:type]          >= 'ln:AutomatedDecision'",
	"       and recommendation[prov:type]    >= 'ln:AutomatedLoanRecommendation'",
	"       and application[prov:type]       >= 'ln:LoanApplication'",
	"       and ourdata[prov:type]           >= 'pl:Controlled'",

	"     group by decision aggregate application,ourdata with Seq",
	")",

	"from (",
	"     select * from features a prov:Entity",

	"     from der1 a prov:WasDerivedFrom",
	"      join features.id=der1.generatedEntity",

	"     from theirdata a prov:Entity",
	"      join der1.usedEntity=theirdata.id",

	"     from der2 a prov:WasDerivedFrom",
	"      join features.id=der2.usedEntity",

	"     from recommendation a prov:Entity",
	"      join der2.generatedEntity=recommendation.id",

	"     from der3 a prov:WasDerivedFrom",
	"      join recommendation.id=der3.usedEntity",

	"     from decision_ a prov:Entity",
	"      join der3.generatedEntity=decision_.id",


	"     from der4 a prov:WasDerivedFrom",
	"      join decision_.id=der4.generatedEntity",

	"     from application a prov:Entity",
	"      join der4.usedEntity=application.id",


	"     where decision_[prov:type] >= 'ln:AutomatedDecision'",
	"       and recommendation[prov:type] >= 'ln:AutomatedLoanRecommendation'",
	"       and application[prov:type] >= 'ln:LoanApplication'",
	"       and theirdata[prov:type] !>= 'pl:Controlled'",

	"     group by decision_ aggregate application,theirdata with Seq",

	")",
	"join decision.id=decision_.id"

    ],



	"sentence": {
		"type": "clause",

		"subject": {
			"type": "noun_phrase",
			"head": "the loan application"},

		"verb": "was automatically approved",



		"complements": [

			{
				"type": "preposition_phrase",
				"preposition": "based on a combination of",
				"noun": {
					"type": "coordinated_phrase",
					"conjunction": "and",
					"@iterator": {
						"type": "@iterator",
						"@variable": "ourdata",
						"@clause": "coordinates",
						"@element": {
							"type": "@funcall",
							"@object": "ourdata",
							"@property":  "prov:type",
							"@function": "lookup-type",
							"@arg1": "noun_phrase",
							"@arg2": "ln"}
					}
				}
			},
			{
				"type": "preposition_phrase",
				"preposition": "and third party data: ",
				"noun": {
					"type": "coordinated_phrase",
					"conjunction": "and",
					"@iterator": {
						"type": "@iterator",
						"@variable": "theirdata",
						"@clause": "coordinates",
						"@element": {
							"type": "@funcall",
							"@object": "theirdata",
							"@property":  "prov:type",
							"@function": "lookup-type",
							"@arg1": "noun_phrase",
							"@arg2": "ln"}
					}
				}
			}

		],
		"features" : {"tense": "past"}


	},

	"context": {
		"ex": "http://example.org/#",
		"foaf": "http://xmlns.com/foaf/0.1/",
		"ln": "https://plead-project.org/ns/loan#",
		"pd": "https://pandas.pydata.org/#"
	}


}

=== lucmoreau/ProvToolbox/modules-explanations/prov-explanations/src/main/resources/nlg/templates/plead.cs/plead.rectification.accept1.json
{

	"select": {
		"decision":       {"@type": "prov:Entity"},
		"request":        {"@type": "prov:Entity"},
		"officer":        {"@type": "prov:Agent"},
		"reviewing":      {"@type": "prov:Activity"},
		"assoc":          {"@type": "prov:WasAssociatedWith"},
		"der1":           {"@type": "prov:WasDerivedFrom"}},

	"query": [

		"prefix ln <https://plead-project.org/ns/loan#>",
		"prefix pl <https://plead-project.org/ns/plead#>",


		"select * from waw a prov:WasAssociatedWith",
		"from officer a prov:Agent",
		" join waw.agent = officer.id",
		"from reviewing a prov:Activity",
		" join waw.activity=reviewing.id",

		"from der1 a prov:WasDerivedFrom",
		" join reviewing.id=der1.activity",
		"from decision a prov:Entity",
		" join der1.generatedEntity=decision.id",
		"from request a prov:Entity",
		" join der1.usedEntity=request.id",


		"where officer[prov:type]     >= 'prov:Person'",
		"  and decision[prov:type]    >= 'pl:ReviewDecision'",
		"  and decision[prov:type]    >= 'pl:AcceptingDecision'",
		"  and request[prov:type]     >= 'pl:DataRectifyRequest'"

	],



	"sentence": {
		"type": "clause",
		"subject": {
			"type": "noun_phrase",
			"determiner": "a",
			"head": {
				"type": "@funcall",
				"@object": "officer",
				"@field":  "id",
				"@function": "noun+localname",
				"@arg1":   "agent"
			},
			"complements": [
				{
					"type": "clause",
					"complementiser": "whose",
					"subject": "decision",
					"verb": "is based on",
					"features" : {"tense": "past"},
					"object": {
						"type": "noun_phrase",
						"determiner": "your",
						"post-modifiers": [
							{
							"type": "noun_phrase",
							"head": "["
							},
							{
							"type":"noun_phrase",
							"head": {
								"type": "@funcall",
								"@object": "request",
								"@field":  "pl:reasons_request",
								"@function": "identity"
							},
							"features": {
								"markup_element": "span",
								"markup_attributes": {
									"type": "@funcall",
									"@object": "request",
									"@function": "markup-for-id",
									"@field":  "id",
									"@arg1": "provelement"
								}
							}},
							{
								"type": "noun_phrase",
								"head": "]"
							}
						],
						"head": "reason"}


				}
			]
		},
		"object": {
			"type": "noun_phrase",
			"determiner": "the",
			"head": "rectification request",
			"post-modifiers": [{
				"type":"noun_phrase",
				"head": {
					"type": "@funcall",
					"@object": "request",
					"@field":  "id",
					"@function": "noun+localname",
					"@arg1": ""
				}}
			]
		},

		"verb": "review",
		"features" : {
			"tense": "past",
			"passive": "true"
		}


	},

	"context": {
		"ex": "http://example.org/#",
		"foaf": "http://xmlns.com/foaf/0.1/",
		"ln": "https://plead-project.org/ns/loan#",
		"pl": "https://plead-project.org/ns/plead#",
		"pd": "https://pandas.pydata.org/#"
	}


}

=== lucmoreau/ProvToolbox/modules-explanations/nlg-spec-transformer/src/test/resources/nlg/templates/todelete/loan.origin/exclusion1.json
{
	"select": {"recommendation": {"@type": "prov:Entity"}},

	"query": [

		"prefix ln <https://plead-project.org/ns/loan#>",
		"prefix sk <https://scikit-learn.org/stable/modules/generated/sklearn.>",
		"prefix pl <https://plead-project.org/ns/plead#>",
		"prefix pd <https://pandas.pydata.org/#>",


		"select * from recommendation a prov:Entity",
		"from wdf a prov:WasDerivedFrom",
		" join recommendation.id=wdf.generatedEntity",
		"from  features a prov:Entity",
		" join wdf.usedEntity=features.id",
		"from wdf0 a prov:WasDerivedFrom",
		" join features.id=wdf0.generatedEntity",
		"from data a prov:Entity",
		" join wdf0.usedEntity=data.id",

		"where features[prov:type] >= 'pd:Series'",
		"and   recommendation[prov:type] >= 'ln:AutomatedLoanRecommendation'",

		"group by recommendation, features aggregate data with Seq"



	],

	"sentence": {
		"type": "clause",
		"object":  {
			"type": "coordinated_phrase",
			"conjunction": "and",
			"@posteval": {
				"@key": "coordinates",
				"@function": "difference-lookup-attribute",
				"@iterator": {
					"@variable": "data",
					"@clause": "@arg1",
					"@element": {
						"@splice": {
							"@object": "data",
							"@property":  "@attributes",
							"@function": "flatten"}
					}},
				"@arg2": {
					"@object": "features",
					"@property":  "@attributes",
					"@function": "flatten"}}},
		"verb": "are",
		"subject": {
			"type": "noun_phrase",
			"determiner": "the",
			"head": "data",
			"complements": [
				{
					"type": "clause",
					"complementiser": "that",
					"subject": "##company",
					"verb": "exclude",
					"features": {
						"tense": "past"
					},
					"complements": [
						{
							"type": "preposition_phrase",
							"preposition": "for the processing of",
							"noun": {
								"type": "noun_phrase",
								"head": "loan application",
								"specifier": "##borrower-possessive"
							}

						}
					]
				}
			]
		},


		"features" : {"tense": "present", "number": "plural"}

	},

	"context": {
		"ex": "http://example.org/#",
		"foaf": "http://xmlns.com/foaf/0.1/",
		"ln": "https://plead-project.org/ns/loan#",
		"pd": "https://pandas.pydata.org/#",
		"py": "urn:python:var:",
		"sk": "https://scikit-learn.org/stable/modules/generated/sklearn."
	}


}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/plead.cs/plead.cs-6b.json
{
  "select": {
    "decision": {
      "@type": "prov:Entity"
    },
    "request": {
      "@type": "prov:Entity"
    },
    "officer": {
      "@type": "prov:Agent"
    },
    "reviewing": {
      "@type": "prov:Activity"
    },
    "assoc": {
      "@type": "prov:WasAssociatedWith"
    },
    "der1": {
      "@type": "prov:WasDerivedFrom"
    }
  },
  "query": [
    "prefix cs <http://openprovenance.org/ns/creditscoring#>",
    "prefix pl <http://openprovenance.org/ns/plead#>",
    "prefix app <https://explain.openprovenance.org/creditscoring/>",
    "select * from recommendation a prov:Entity",
    "where recommendation[prov:type] >= 'pl:AutomatedRecommendation'"
  ],
  "sentence": {
    "type": "paragraph",
    "items": [
      {
        "type": "clause",
        "subject": {
          "type": "noun_phrase",
          "determiner": "The",
          "head": "recommendation",
          "post-modifiers": [
            {
              "type": "preposition_phrase",
              "preposition": "of",
              "noun": {
                "type": "noun_phrase",
                "determiner": "the",
                "head": "system"
              }
            }
          ]
        },
        "verb": {
          "type": "verb_phrase",
          "head": "was",
          "post-modifiers": [
            {
              "type": "preposition_phrase",
              "preposition": "to",
              "noun": "refuse"
            }
          ]
        },
        "object": {
          "type": "noun_phrase",
          "head": "application",
          "specifier": "##borrower-possessive"
        },
        "complements": [
          {
            "type": "clause",
            "indirect_object": {
              "type": "preposition_phrase",
              "preposition": "of",
              "noun": {
                          "type": "@funcall",
                          "@object": "recommendation",
                          "@property": "pl:reason",
                          "@function": "lookup-type",
                          "@arg1": "noun_phrase",
                          "features": {
                              "head_markup_element": "span",
                              "head_markup_attributes": {
                                  "type": "@funcall",
                                  "@object": "recommendation",
                                  "@function": "markup-for-id",
                                  "@field":  "id",
                                  "@arg1": "provelement"
                              }
                          }
                        }
            },
            "complementiser": "because"
          }
        ],
        "features": {
          "type": "features",
          "tense": "past"
        }
      }
    ],
    "properties": {}
  },
  "context": {
  "ex": "http://example.org/#",
    "app": "https://explain.openprovenance.org/creditscoring/",
    "pl": "http://openprovenance.org/ns/plead#",
    "cs": "http://openprovenance.org/ns/creditscoring#"
  }
}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/plead/plead.erasure.accept2b.json
{

	"select": {
		"decision":       {"@type": "prov:Entity"},
		"application":    {"@type": "prov:Entity"},
		"officer":        {"@type": "prov:Agent"},
		"erasing":        {"@type": "prov:Activity"},
		"assoc":          {"@type": "prov:WasAssociatedWith"},
		"wib":            {"@type": "prov:WasInvalidatedBy"},
		"wsb1":           {"@type": "prov:WasStartedBy"}},

	"query": [

		"prefix ln <https://plead-project.org/ns/loan#>",
		"prefix pl <https://plead-project.org/ns/plead#>",


		"select * from waw a prov:WasAssociatedWith",
		"from officer a prov:Agent",
		" join waw.agent = officer.id",
		"from erasing a prov:Activity",
		" join waw.activity=erasing.id",

		"from wsb1 a prov:WasStartedBy",
		" join erasing.id=wsb1.activity",
		"from decision a prov:Entity",
		" join wsb1.trigger=decision.id",
		"from wib a prov:WasInvalidatedBy",
		" join erasing.id=wib.activity",
		"from application a prov:Entity",
		" join wib.entity=application.id",


		"where officer[prov:type]     >= 'prov:Person'",
		"  and decision[prov:type]    >= 'pl:ReviewDecision'",
		"  and decision[prov:type]    >= 'pl:AcceptanceDecision'",
		"  and application[prov:type]     >= 'ln:LoanApplication'",

		"group by decision,officer, erasing,wib aggregate application with Seq"

	],



	"sentence": {
		"type": "clause",
		"object": {
			"type": "noun_phrase",
			"determiner": "the",
			"features": {"number": "plural"},
			"head": "data",
			"pre-modifiers": [{
				"type":"adjective_phrase",
				"head":"following"}]
		},
		"indirect_object": {
			"type": "preposition_phrase",
			"preposition": "on",
			"noun": {
				"type": "@funcall",
				"@object": "wib",
				"@property": "ln:at",
				"@optional": "true",
				"@function": "timestring"}
		},
		"verb": "delete",

		"modifiers": [
			{
				"type":  "noun_phrase",
				"head":  ":"
			},
			{
				"type": "coordinated_phrase",
				"conjunction": "and",
				"@iterator": {
					"type": "@iterator",
					"@variable": "application",
					"@clause": "coordinates",
					"@element": {
						"type": "@funcall",
						"@object": "application",
						"@property": "prov:type",
						"@function": "lookup-type",
						"@arg1": "noun_phrase",
						"@arg2": "ln",
						"post-modifiers": [
							{
								"type": "adjective_phrase",
								"head": {
									"type": "@funcall",
									"@object": "application",
									"@field":  "id",
									"@function": "noun+localname",
									"@arg1": ""
								},
								"features": {
									"markup_element": "span",
									"markup_attributes": {
										"type": "@funcall",
										"@object": "application",
										"@function": "markup-for-id",
										"@field":  "id",
										"@arg1": "provelement"
									}
								}
							}
						],
						"features": {
							"head_markup_element": "span",
							"head_markup_attributes": {
								"type": "@funcall",
								"@object": "application",
								"@function": "markup-for-id",
								"@field":  "id",
								"@arg1": "provelement"
							}
						}
					}
				}
			}

		],

		"features" : {"tense": "past", "passive":  "true"}


	},

	"context": {
		"ex": "http://example.org/#",
		"foaf": "http://xmlns.com/foaf/0.1/",
		"ln": "https://plead-project.org/ns/loan#",
		"pl": "https://plead-project.org/ns/plead#",
		"pd": "https://pandas.pydata.org/#"
	}


}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/collabmap/attribution1.json
{

	"select": {"attr": {"@type": "prov:WasAttributedTo"}},

	"query": "select * from attr a prov:WasAttributedTo",

	"sentence": {
		"type": "clause",
		"object":  {
			"type": "noun_phrase",
			"head": {
				"type": "@funcall",
				"@object": "attr",
				"@field":  "entity",
				"@function": "localname"},
			"features": {
				"number": {
					"type": "@funcall",
					"@object": "attr",
					"@field": "entity",
					"@function": "pluralp"}}},
		"verb": "attribute",
		"modifiers": [{
			"type": "preposition_phrase",
			"preposition": "to",
			"noun": {
				"type": "@funcall",
				"@object": "attr",
				"@field": "agent",
				"@function": "localname"}}],
		"features" : {
			"tense": "past",
			"passive": "true"}

	},

	"context": {
		"ex": "http://example.org/#"
	}


}
