=== lucmoreau/ProvToolbox/modules-explanations/nlg-spec-transformer/src/test/resources/jsonschema/xplan.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "definitions" : {
        "Determiner": {
            "description": "a determiner",
            "type": "string"
        },
        "Phrase": {
            "OneOf": [
                {
                    "$ref": "#/definitions/Clause"
                }
            ]
        },
        "Verb": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Clause"
                }
            ]
        },
        "Object": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Funcall"
                },
                {
                    "$ref": "#/definitions/Clause"
                }
            ]
        },
        "Clause": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["clause", "noun_phrase", "verb_phrase", "coordinated_phrase", "preposition_phrase"]
                },
                "determiner": {
                    "$ref": "#/definitions/Determiner"
                },
                "subject": {
                    "$ref": "#/definitions/Phrase"
                },
                "indirect_object": {
                    "$ref": "#/definitions/Phrase"
                },
                "object": {
                    "$ref": "#/definitions/Object"
                },
                "verb": {
                    "$ref": "#/definitions/Verb"
                },
                "head":  {
                    "$ref": "#/definitions/Head"
                },
                "conjunction": {
                    "type": "string"
                },
                "coordinates": {
                    "$ref": "#/definitions/ArrayOfClause"
                },
                "complements": {
                    "$ref": "#/definitions/Complements"
                },
                "front-modifiers": {
                    "$ref": "#/definitions/PreModifiers"
                },
                "pre-modifiers": {
                    "$ref": "#/definitions/PreModifiers"
                },
                "post-modifiers": {
                    "$ref": "#/definitions/PostModifiers"
                },
                "modifiers": {
                    "$ref": "#/definitions/Modifiers"
                },
                "@iterator": {
                    "type": "object"
                },
                "features": {
                    "$ref": "#/definitions/Features"
                }
            },
            "required": [
                "type"
            ],
            "additionalProperties": false
        },
        "StringArray": {
            "description" : "an array of strings",
            "type": "array",
            "items": {
                "type" : "string"
            }
        },
        "Funcall": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": ["@funcall"]
                },
                "@object": {
                    "type": "string"
                },
                "@field": {
                    "type": "string"
                },
                "@function": {
                    "type": "string"
                },
                "@arg1": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "type",
                "@object",
                "@field",
                "@function"
            ]
        },
        "StringOrFuncall": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Funcall"
                }
            ]
        },
        "Head": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/Funcall"
                }
            ]
        },
        "ArrayOfClause": {
            "description" : "an array of clause",
            "type": "array",
            "items": {
                "type" : "object"
            }
        },
        "ArrayOfWhere": {
            "description" : "an array of where clause",
            "type": "array",
            "items": {
                "$ref": "#/definitions/Clause"
            }
        },
        "Query": {
            "OneOf": [
                {
                    "type": "string"
                },
                {
                    "$ref": "#/definitions/StringArray"
                }
            ]
        },

        "Complements": {
            "OneOf": [
                {
                    "type": "array"
                },
                {
                    "type": "object"
                }
            ]
        },
        "Features": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "tense": {
                    "type": "string"
                },
                "passive": {
                    "type": "string"
                },
                "number": {
                    "$ref": "#/definitions/StringOrFuncall"
                },
                "head_markup_element": {
                    "type": "string"
                },
                "head_markup_attributes": {
                    "$ref": "#/definitions/Funcall"
                }
            },
            "additionalProperties": false
        },
        "PreModifiers": {
            "type": "array"
        },
        "Modifiers": {
            "type": "array"
        },
        "PostModifiers": {
            "type": "array"
        }
    },
    "properties": {
        "select": {
            "type": "object"
        },
        "query": {
            "$ref": "#/definitions/Query"
        },
        "where": {
            "$ref": "#/definitions/ArrayOfClause"
        },
        "sentence": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["paragraph", "clause", "coordinated_phrase"]
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Clause"
                    }
                },
                "properties": {
                    "type": "object"
                },
                "subject": {
                    "$ref": "#/definitions/Clause"
                },
                "object": {
                    "$ref": "#/definitions/Object"
                },
                "indirect_object": {
                    "$ref": "#/definitions/Phrase"
                },
                "verb": {
                    "type": "string"
                },
                "features": {
                    "$ref": "#/definitions/Features"
                },
                "complements": {
                    "$ref": "#/definitions/Complements"
                },
                "modifiers": {
                    "$ref": "#/definitions/Modifiers"
                },
                "post-modifiers": {
                    "$ref": "#/definitions/PostModifiers"
                },
                "conjunction": {
                    "type": "string"
                },
                "coordinates": {
                    "$ref": "#/definitions/ArrayOfClause"
                }
            },
            "additionalProperties": false
        },
        "context": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        }
    },
    "required": [
        "select",
        "sentence",
        "context"
    ],
    "additionalProperties": false
}

=== lucmoreau/ProvToolbox/modules-explanations/nlg-spec-transformer/src/test/resources/nlg/templates/todelete/loan.origin/responsibility2.json
{
    "select": {"recommendation": {"@type": "prov:Entity"},

	       "pipeline2":      {"@type": "prov:Entity"},
	       "actor2":         {"@type": "prov:Agent"},
	       "do2":            {"@type": "prov:Activity"},	       
	       "wdf2":           {"@type": "provext:WasDerivedFromPlus"},
	       "wgb2":           {"@type": "prov:WasGeneratedBy"},	       
	       "waw2":           {"@type": "prov:WasAssociatedWith"},
	       
	       "pipeline3":      {"@type": "prov:Entity"},
	       "actor3":         {"@type": "prov:Agent"},
	       "do3":            {"@type": "prov:Activity"},	       
	       "wdf3":           {"@type": "provext:WasDerivedFromPlus"},
	       "wgb3":           {"@type": "prov:WasGeneratedBy"},	       
	       "waw3":           {"@type": "prov:WasAssociatedWith"}},

    "query": [
	"prefix ln <https://plead-project.org/ns/loan#>",
	"prefix sk <https://scikit-learn.org/stable/modules/generated/sklearn.>",
	"prefix ex <http://example/org>",

	"select * from waw a prov:WasAssociatedWith",
	"from actor a prov:Agent",
	" join waw.agent = actor.id",
	"from do a prov:Activity",
	" join waw.activity=do.id",

	"from wgb a prov:WasGeneratedBy",
	" join do.id=wgb.activity",
	"from pipeline a prov:Entity",
	" join wgb.entity=pipeline.id",
	"from wdf a prov:WasDerivedFrom",
	" join pipeline.id=wdf.usedEntity",
	"from recommendation a prov:Entity",
	" join wdf.generatedEntity=recommendation.id",


	"from wdf2 a prov:WasDerivedFrom",
	" join pipeline.id=wdf2.generatedEntity",
	"from pipeline2 a prov:Entity",
	" join wdf2.usedEntity=pipeline2.id",
	"from wgb2 a prov:WasGeneratedBy",
	" join pipeline2.id=wgb2.entity",
	"from do2 a prov:Activity",
	" join wgb2.activity=do2.id",

	"from waw2 a prov:WasAssociatedWith",
	" join do2.id=waw2.activity",
	"from actor2 a prov:Agent",
	" join waw2.agent = actor2.id",


	"where actor[prov:type]          >= 'prov:Person'",
	"  and recommendation[prov:type] >= 'ln:AutomatedLoanRecommendation'",
	"  and do [prov:type]            >= 'ln:PipelineApproval'",
	"  and pipeline [prov:type]      >= 'sk:pipeline.Pipeline'",
	"  and pipeline2[prov:type]      >= 'sk:pipeline.Pipeline'",
	"  and do2[prov:type]            >= 'ex:DataFitting'"

    ],

    "where": [{"@object":    "recommendation",
	       "@property":  "prov:type",
	       "@function":  "includesQualifiedName",
	       "@arg1":      "ln:AutomatedLoanRecommendation"},

	      {"@object":    "pipeline2",
	       "@property":  "prov:type",
	       "@function":  "includesQualifiedName",
	       "@arg1":      "sk:pipeline.Pipeline"},
	      {"@object":    "actor2",
	       "@property":  "prov:type",
	       "@function":  "includesQualifiedName",
	       "@arg1":      "prov:Person"},
	      {"@object":    "do2",
	       "@property":  "prov:type",
	       "@function":  "includesQualifiedName",
	       "@arg1":      "ln:PipelineApproval"},	      

	      {"@object":    "pipeline3",
	       "@property":  "prov:type",
	       "@function":  "includesQualifiedName",
	       "@arg1":      "sk:pipeline.Pipeline"},
	      {"@object":    "actor3",
	       "@property":  "prov:type",
	       "@function":  "includesQualifiedName",
	       "@arg1":      "prov:Person"},
	      {"@object":    "do3",
	       "@property":  "prov:type",
	       "@function":  "includesQualifiedName",
	       "@arg1":      "ln:DataFitting"},	      
	      
	      {"@object":    "waw2",
	       "@field":     "activity",
	       "@function":  "equals",
	       "@object1":   "do2",
	       "@field1":    "id"},
	      {"@object":    "waw2",
               "@field":     "agent",
	       "@function":  "equals",
	       "@object1":   "actor2",
	       "@field1":    "id"},

	      
	      {"@object":    "wgb2",
	       "@field":     "activity",
	       "@function":  "equals",
	       "@object1":   "do2",
	       "@field1":    "id"},
	      {"@object":    "wgb2",
               "@field":     "entity",
	       "@function":  "equals",
	       "@object1":   "pipeline2",
	       "@field1":    "id"},
	      
	      {"@object":    "wdf2",
	       "@field":     "usedEntity",
	       "@function":  "equals",
	       "@object1":   "pipeline2",
	       "@field1":    "id"},
	      {"@object":    "wdf2",
               "@field":     "generatedEntity",
	       "@function":  "equals",
	       "@object1":   "recommendation",
	       "@field1":    "id"},


	      {"@object":    "waw3",
	       "@field":     "activity",
	       "@function":  "equals",
	       "@object1":   "do3",
	       "@field1":    "id"},
	      {"@object":    "waw3",
               "@field":     "agent",
	       "@function":  "equals",
	       "@object1":   "actor3",
	       "@field1":    "id"},

	      
	      {"@object":    "wgb3",
	       "@field":     "activity",
	       "@function":  "equals",
	       "@object1":   "do3",
	       "@field1":    "id"},
	      {"@object":    "wgb3",
               "@field":     "entity",
	       "@function":  "equals",
	       "@object1":   "pipeline3",
	       "@field1":    "id"},
	      
	      {"@object":    "wdf3",
	       "@field":     "usedEntity",
	       "@function":  "equals",
	       "@object1":   "pipeline3",
	       "@field1":    "id"},
	      {"@object":    "wdf3",
               "@field":     "generatedEntity",
	       "@function":  "equals",
	       "@object1":   "recommendation",
	       "@field1":    "id"}],    

    "sentence": {
	"type": "clause",
	"subject": {"type": "noun_phrase",
		    "head": "responsibility",
		    "post-modifiers": [
			{"type": "preposition_phrase",
			 "preposition": "for",
			 "noun":  {"type":"noun_phrase",
				   "determiner": "the",
				   "head": {"@object": "recommendation",
					    "@field":  "id",
					    "@function": "noun+localname",
					    "@arg1": "recommendation"}}}
		    ]},
	"verb": "is",
	"modifiers": [{"type": "preposition_phrase",
		       "preposition": "with",
		       "noun":  {"type":"noun_phrase",
				 "determiner": "the",
				 "head": {"@object": "actor",
					  "@field":  "id",
					  "@function": "noun+localname",
					  "@arg1": "agent"}}},
		     {"type": "preposition_phrase",
		       "preposition": "for",
		       "noun":  {"type":"noun_phrase",
				 "head": {"@object": "do",
					  "@field":  "id",
					  "@function": "noun+localname",
					  "@arg1": "approval"}}},
		     {"type": "preposition_phrase",
		       "preposition": "with",
		       "noun":  {"type":"noun_phrase",
				 "determiner": "the",
				 "head": {"@object": "actor",
					  "@field":  "id",
					  "@function": "noun+localname",
					  "@arg1": "agent"}}},
		     {"type": "preposition_phrase",
		       "preposition": "for",
		       "noun":  {"type":"noun_phrase",
				 "head": {"@object": "do",
					  "@field":  "id",
					  "@function": "noun+localname",
					  "@arg1": "data fitting"}}}],
	
	"features" : {"tense": "past"}

    },

    "context": {
	"ex": "http://example.org/#",	
	"foaf": "http://xmlns.com/foaf/0.1/",
	"ln": "https://plead-project.org/ns/loan#",
	"pd": "https://pandas.pydata.org/#",
	"py": "urn:python:var:",
	"sk": "https://scikit-learn.org/stable/modules/generated/sklearn."
    }
    
    
}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/collabmap/derivation-verification1.json
{
	"select": {"der": {"@type": "prov:WasDerivedFrom"}},

	"query": [
		"prefix collabmap <http://www.orchid.ac.uk/ontologies/collabmap.owl#>",

		"select * from der a prov:WasDerivedFrom",
		"from vote a prov:Entity",
		" join der.generatedEntity=vote.id",
		"from routeset a prov:Entity",
		" join der.usedEntity=routeset.id",
		"from wgb a prov:WasGeneratedBy",
		" join der.generatedEntity=wgb.entity",
		"from activity a prov:Activity",
		" join wgb.activity=activity.id",


		"where der[prov:type]     >= 'collabmap:votedOn'",
		"  and routeset[prov:type]>= 'collabmap:RouteSet'",
		"  and vote[prov:type]    >= 'collabmap:Vote'",
		"  and activity[prov:type]>= 'collabmap:CompletionVerification'"
	],

	"sentence": {
		"type": "clause",
		"object":  {
			"type": "noun_phrase",
			"head": "the route set",
			"post-modifiers": [
				{
					"type": "noun_phrase",
					"head": {
						"type": "@funcall",
						"@object": "routeset",
						"@field":  "id",
						"@function": "localname"
					}
				}
			]
		},
		"verb": "vote on",
		"post-modifiers": [
			{
				"type": "@funcall",
				"@object": "vote",
				"@property": "prov:value",
				"@function": "lookup-attribute",
				"@arg1": "adverb_phrase"
			},
			{
				"type": "preposition_phrase",
				"preposition": "during",
				"noun": {
					"type": "noun_phrase",
					"head": "activity",
					"post-modifiers": [
						{
							"type": "noun_phrase",
							"head": {
								"type": "@funcall",
								"@object": "activity",
								"@field":  "id",
								"@function": "localname"
							}
						}
					]
				}
			},
			{
				"type": "preposition_phrase",
				"preposition": "at",
				"noun": {
					"type": "@funcall",
					"@object": "wgb",
					"@field": "time",
					"@optional": "true",
					"@function": "timestring"
				}
			}
		],

		"features" : {
			"tense": "past",
			"passive": "true"
		}
	},

	"context": {
		"ex": "http://example.org/#",
		"collabmap": "http://www.orchid.ac.uk/ontologies/collabmap.owl#"
	}

}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/plead.cs/plead.cs-1a.json
{
  "select": {
    "decision": {
      "@type": "prov:Entity"
    },
    "request": {
      "@type": "prov:Entity"
    },
    "officer": {
      "@type": "prov:Agent"
    },
    "reviewing": {
      "@type": "prov:Activity"
    },
    "assoc": {
      "@type": "prov:WasAssociatedWith"
    },
    "der1": {
      "@type": "prov:WasDerivedFrom"
    }
  },
  "query": [
    "prefix cs <http://openprovenance.org/ns/creditscoring#>",
    "prefix pl <http://openprovenance.org/ns/plead#>",
    "prefix app <https://explain.openprovenance.org/creditscoring/>",
    "select * from decision a prov:Entity",
    "from der1 a prov:WasDerivedFrom",
    " join decision.id = der1.generatedEntity",
    "from application a prov:Entity",
    " join der1.usedEntity = application.id",
    "where decision.id >= 'app:applications/437/decision'",
    "and decision[prov:type] >= 'pl:Decision'",
    "and application[prov:type] >= 'cs:CreditCardApplication'"
  ],
"sentence": {
    "type": "paragraph",
    "items": [
      {
        "type": "clause",
        "subject": "##company",
        "verb": "regret",
        "object": {
          "type": "verb_phrase",
          "head": "to inform",
          "object": {
            "type": "noun_phrase",
            "head": "you"
          },
          "complements": [
            {
              "type": "clause",
              "verb": "decline",
              "object": {
                                "type": "@funcall",
                                "@object": "application",
                                "@property": "prov:type",
                                "@function": "lookup-type",
                                "@arg1": "noun_phrase",
                                "@arg2": "cs",
                                "post-modifiers": [
                                    {
                                        "type": "adjective_phrase",
                                        "head": {
                                            "type": "@funcall",
                                            "@object": "application",
                                            "@field":  "id",
                                            "@function": "noun+localname",
                                            "@arg1": ""
                                        },
                                        "features": {
                                            "markup_element": "span",
                                            "markup_attributes": {
                                                "type": "@funcall",
                                                "@object": "application",
                                                "@function": "markup-for-id",
                                                "@field":  "id",
                                                "@arg1": "provelement"
                                            }
                                        }
                                    }
                                ],
                                "features": {
                                    "head_markup_element": "span",
                                    "head_markup_attributes": {
                                        "type": "@funcall",
                                        "@object": "application",
                                        "@function": "markup-for-id",
                                        "@field":  "id",
                                        "@arg1": "provelement"
                                    }
                                }
                            },
              "features": {
                "type": "features",
                "tense": "past",
                "passive": "true"
              }
            }
          ]
        }
      },
      {
        "type": "clause",
        "subject": "That",
        "verb": "is",
        "object": {
          "type": "clause",
          "subject": {
                          "type": "@funcall",
                          "@object": "decision",
                          "@property": "pl:reason",
                          "@function": "lookup-type",
                          "@arg1": "noun_phrase",
                          "features": {
                              "head_markup_element": "span",
                              "head_markup_attributes": {
                                  "type": "@funcall",
                                  "@object": "decision",
                                  "@function": "markup-for-id",
                                  "@field":  "id",
                                  "@arg1": "provelement"
                              }
                          }
                        },
          "complementiser": "because of"
        }
      }
    ],
    "properties": {}
  },
  "context": {
"ex": "http://example.org/#",
    "app": "https://explain.openprovenance.org/creditscoring/",
    "pl": "http://openprovenance.org/ns/plead#",
    "cs": "http://openprovenance.org/ns/creditscoring#"
  }
}

=== lucmoreau/ProvToolbox/modules-explanations/nlg-spec-transformer/src/test/resources/nlg/templates/baking/baking-generation2.json
{

    "select": {"gen": {"@type": "prov:WasGeneratedBy"},
	       "act": {"@type": "prov:Activity"},
	       "waw": {"@type": "prov:WasAssociatedWith"}},



    "query": [
	"prefix ex <http://example.org/#>",
	"select * from  gen a prov:WasGeneratedBy",
	"from act a prov:Activity",
	"join gen.activity = act.id",
	"from waw a prov:WasAssociatedWith",
	"join act.id = waw.activity",
	"where act[prov:type] >= 'ex:Baking' "],

    

    "sentence": {
	"type": "clause",
	"object":  {"type": "noun_phrase",
		    "head": {"@object": "gen",
			     "@field":  "entity",
			     "@function": "localname"},
		    "features": {"number": {"@object": "gen",
					    "@field": "entity",
					    "@function": "pluralp"}}},
	"verb": "bake",
	"modifiers": [{"type": "preposition_phrase",
		       "preposition": "by",
		       "noun": {"@object": "waw",
				"@field": "agent",
				"@optional": "true",				
				"@function": "localname"}},
		      {"type": "preposition_phrase",
		       "preposition": "at",
		       "noun": {"@object": "gen",
				"@field": "time",
				"@optional": "true",				
				"@function": "timestring"}}],	
	"features" : {"tense": "past",
		      "passive": "true"}

    },

    "context": {
	"ex": "http://example.org/#"
    }
    
    
}

=== lucmoreau/ProvToolbox/modules-executable-provman/src/test/resources/xplans/thump/thump.plan.failure1a.json
{

	"select": {
		"plan1":        {"@type": "prov:Entity"},
		"plan2":        {"@type": "prov:Entity"},
		"ag":           {"@type": "prov:Agent"}
		},
	"query": [
		"prefix ros <https://openprovenance.org/ns/ros>",
		"prefix rpl <http://openprovenance.org/ns/rosplan>",
		"prefix rs <urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/>",
		"prefix rn <urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/nodes/>",
		"prefix msg <urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/messages/>",
		"prefix ex <http://example.org/>",

		"prefix pl <https://plead-project.org/ns/plead#>",

		"select * from wdf a prov:WasDerivedFrom",
		"from plan1 a prov:Entity",
		" join wdf.usedEntity = plan1.id",
		"from plan2 a prov:Entity",
		" join wdf.generatedEntity=plan2.id",
		"from usd a prov:Used",
		" join plan1.id = usd.entity",
		"from dispatching a prov:Activity",
		" join usd.activity=dispatching.id",
		"from waw a prov:WasAssociatedWith",
		" join dispatching.id=waw.activity",
		"from ag a prov:Agent",
		" join waw.agent=ag.id",

		"where plan2[prov:type]       >= 'rpl:CancelledPlan'",
		"  and plan1[prov:type]       >= 'rpl:EsterelPlan'",
		"  and ag[prov:type]          >= 'rpl:ROSPlanNode'",
		"  and dispatching[prov:type] >= 'ex:DispatchingPlan'"


	],



	"sentence": {
		"type": "clause",
		"object": {
			"type": "noun_phrase",
			"determiner": "the",
			"head": {
				"type": "@funcall",
				"@object": "plan1",
				"@field":  "id",
				"@function": "noun+localname",
				"@arg1":   "plan"
			},
			"complements": [
				{
					"type": "clause",
					"complementiser": "which",
					"verb": "dispatch",
					"features": {
						"tense": "past",
						"passive": "true"
					},
					"subject": {
						"type": "noun_phrase",
						"determiner": "the",
						"head": {
							"type": "@funcall",
							"@object": "ag",
							"@field":  "id",
							"@function": "noun+localname",
							"@arg1":   "dispatcher"
						}
					},
					"modifiers": [
						{
							"type": "preposition_phrase",
							"preposition": "during",
							"noun": {
								"type": "@funcall",
								"@object": "dispatching",
								"@field": "id",
								"@function": "noun+localname",
								"@arg1":   "activity"}
						}
					]


				}
			]
		},

		"verb": "cancel",
		"features" : {
			"tense": "past",
			"passive": "true"
		}


	},

	"context": {
		"ex": "http://example.org/#",
		"foaf": "http://xmlns.com/foaf/0.1/",
		"ln": "https://plead-project.org/ns/loan#",
		"pl": "https://plead-project.org/ns/plead#",
		"pd": "https://pandas.pydata.org/#",
		"ros": "https://openprovenance.org/ns/ros",
		"rpl": "http://openprovenance.org/ns/rosplan",
		"rs": "urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2",
		"rn": "urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/nodes/",
		"msg": "urn:uuid:e760c81c-0e64-11eb-bcbf-000c292939e2/messages/"


	}


}
